### ISSUE TITLE
发布不了文章

### ISSUE THREAD

**Issue by ljg208** [lihangleo2/RichEditTextCopyToutiao#1]
demo中的richEditor.getHtml() 为null

**Comment by lihangleo2** [comment]
怎么可能呢 你运行我的demo了没。编辑了内容，richEditor.getHtml() 还是为null？

**Comment by ljg208** [comment]
运行了，输入内容，发布按钮一直灰的 ，不可点击；编辑内容，richEditor.getHtml()为null 魅族android8.0

**Comment by lihangleo2** [comment]
意思是编辑内容的时候正常，在获取内容的时候 获取不到么？能否用你手机测试下  把日志发我看下。或者能否加下我qq,我们一起解决下。没有魅族测试机

**Comment by ljg208** [comment]
是的，编辑内容正常，获取不到内容，应该是没有回调callback方法，你的qq多少我加你。

**Comment by lihangleo2** [comment]
兄弟 。，问题找到了。  我更新下 。好了 在这里喊你， 你再试试。感谢

**Comment by lihangleo2** [comment]
bug已修复。兄弟，可以去试试。如果还有问题的话，再把这个issues打开。

**Comment by vastsea88** [comment]
华为 android 8.0也是同样问题
